apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:R/KseDI=,iv:OePW4b0jx/Pg5VWBFQWgfOL2/YjysHkCdSz9F9oL8Hs=,tag:uJcV17j4eZtQVDwdra1HQg==,type:str]
    admin-password: ENC[AES256_GCM,data:DcUTvaLeKifQQr1A,iv:hei1QHvkbJ2EnqXq5jg+DpzPW1KNFW59EWXg2vtW5iU=,tag:E/pZG3UtvrFofHyF3fagNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQTRJUUcvTTYrQjB6T3Nv
            c0VobDF0Y0hPWEZaNThVNlUvVTEyTldXWkM0CmZXTTBCQmtnRmY4bloyZStVK0pW
            ZVQvZ0tnUUpwUlQzTDRhYngrSmN4TG8KLS0tIGdnT2p0eHVhQkdiZDVia3dDaEZM
            Skd2enpMTlZVTXhwVllKaUJvRzR4eFEKeOeKJLjdUfjrlj8agvjkHrQDODm/eknE
            7Y6HYuY3yTDbxmpgAFYFJxiFkRcbNSBqke/+Cj2MAfnjqM7nwIyxTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-25T08:41:24Z"
    mac: ENC[AES256_GCM,data:2BtFjcx1B2I1eWTJdHjL1PtSCR+PMOFpj2a7WrSSSP9C0ySA8rK79T92BJLBZmyR9nrmOjd326XHCTsw9KeRSvHJFRWXrVu79Sacj4hllop1v42K+M6RcI+PkdWU41NqXAuMyPW8DKPf4UApeGHlMhjnd5PaI6RTAUeK7qQj4z8=,iv:mJ0bipaklbOiCBVDGfgbUu1qKeKpujUCR1XpwJHCBxU=,tag:ynuxP5wc0DgD4jCTMgeARQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
