apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <APP_NAME>-data-pvc
  namespace: <APP_NAME>
  labels:
    app.kubernetes.io/name: <APP_NAME>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
