apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-tls
  namespace: default
spec:
  secretName: authelia-tls-cert
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - auth.littlehomelab.com
