apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - certificate.yaml
  - authelia-secret.sops.yaml
  - secret.sops.yaml
  - middleware.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml
