apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: default
type: Opaque
stringData:
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:OyEepFWEckH4W0pjxKShaeQMM4HhRtNaJK0LCONBzXLJHpyleM0K/eswXEFiEZxlzir4zLvkjEQT4QcD0vBUrQ==,iv:3b/mYv+828U0alDdjve0LF65+rbEVhSKiPLR5Cls3Og=,tag:oBMRhDkSIQNoyPgCDP+l8Q==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:5xxrlPr9WveHxg/RnL6AbNVEAbjgVTSppbQpYuH96L5uSn/B1Hbfq3I5pOkTZ72+K2mv0fOGQ3ABQyFL7rDpTA==,iv:JwBdIpkGCpTOYt1ecqdMxiAS7gqvqo5cWbZEGTgB71E=,tag:L5kWo/jKhCm2rVl/4yoGzA==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:wG+tAqMj3P3rWexpD9/XkUxjLoB6D2oo4m2wPd3rHTcnHdY71AWVZi4HGTGNzpwpbmfTZaPBMtJvid6mn7o43g==,iv:yezERRrqiYz34Njc576T7iWy0F8ejFKX0MtT5RM88/w=,tag:DyP7NOUJKA4qz8ktFO3x9w==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:Lndx6sGIU2i0r/LmMtXzDCWKPxcA8ds4gBJc/Gf7kWGFh63AIkBStBQJbA9rf8S8u0iKBbPECWWbWgn8wXfV4A==,iv:da3OttbyE+pXC5VoPED9r6gdHutVCeLdmqO3e3OxwEU=,tag:4O1Hv8qtekqKTpn0p4/OZQ==,type:str]
    ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:YW8lSmpSA8wuXpH3fdMFsxziRwGuGO2ZD9BdoldM2ZJae4pLbjLXY9mp9Ajioxy20MCGiA7FJ4XZZzy4wzI/yQ==,iv:IJygOsm3q6nzdb6M5bymiCORDRG4Enlu/NoeLZaUmws=,tag:ZpCLjYrgOKEKETiZjbLWfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzN3ZRNXQyYVhnYmpZVWpt
            SlNBRzFBMGdxNEtabG1EV0ZuL0QvK3kvVHpNCmhsd29IdDVoR3I5YThJcTJPUWdn
            cjVnTTZMd25NWWZXcHJCQ0trNnNFdDQKLS0tIE9TSzZDcmpBa1BtWDcyeWorbWdD
            RGYyVUI0U29mVlAxYnZRUDFPOGU4bzgKV1PUKnTpcoS9WDo39uT8TM56wQrnczS+
            CkwaXxwwAsoNUSaC0aWftPAMe5FwKUB8jynFcVagkre4Auc2GNGPRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T11:07:00Z"
    mac: ENC[AES256_GCM,data:lHsYW0832Ps0tHPt4t0tdLI9yt8YTdlob8JYk5CkqMojC7MEIo4qDIf+K9QVpEHOZ9yP+GknsnfmcOeeY+7S7mKO4nL72zsqfY2MxZVAVFXpKqQa90EJxNdsZTE//Hpm3gQMZW8gT9KNwmkpMd4aNlFVPK590EPgNF7J+oIk1OQ=,iv:SeKR5Ms1Vuzt0CmH6cw2BVBe2y4A/OPd0JGrjmCFJeQ=,tag:LHUC5B4CPaTEvn/1Vm1A+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
