apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bentopdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hidalgowhat/littlehomelab-infra.git'
    targetRevision: HEAD
    path: apps/bentopdf
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bentopdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true