apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: utility-ping
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hidalgowhat/littlehomelab-infra.git'
    targetRevision: HEAD
    path: apps/ping # Points to your raw files in apps/ping
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
