apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://dirsigler.github.io/uptime-kuma-helm
    chart: uptime-kuma
    targetRevision: 2.5.0
    helm:
      values: |
        replicaCount: 1

        service:
          type: ClusterIP
          port: 3001

        ingress:
          enabled: true
          ingressClassName: traefik
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: status.littlehomelab.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: uptime-kuma-tls
              hosts:
                - status.littlehomelab.com
        persistence:
          enabled: true
          storageClass: ""
          accessMode: ReadWriteOnce
          size: 4Gi

        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
