apiVersion: v1
kind: Secret
metadata:
    name: wiki-db-secret
    namespace: wiki
    labels:
        app.kubernetes.io/name: wiki.js
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:xAbD3w==,iv:EjVyP/tYvwFzOMy6p1YlhVlKRJOLsnaYTR33M8cLRLE=,tag:tEjDs5kmX10bcpfitE9I0g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:tpSC0A==,iv:rbHEfGPyHy1SvUPHXEsMHebjTlgKmqjkDXGgx8O96zA=,tag:faE6NuL2WQ+znjsslsTUyg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5VhNWA==,iv:phGqzad8kH3HnTmD2rSpd5mNmSeTc2SoBg4r8Q6QWbw=,tag:0sCcvjuQ/hiybrZRyW3xDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbnVRdnR4ZFlKT2FUT3NS
            NHluTklrVHdwVGNKYjlvMnBIeHNkVjhLK2tJCjlqMUVIcVhpazBGRXJTVCs4TXpn
            SjZUcjc5N3E5WHAzajZ1YlZjTUlzK28KLS0tIFJFdmpkSFUwejJLRllvcEFWRmNs
            YlZxSmdkT0JIR1BUdFhPZXF6VnF6bWcK2CGiaLjlLfpWM9x9jS9wq1zaNqaxtrJW
            g7kqJpF4mP1Q4rN6hDk2Z+CYc8TePIIMZdPG4XrQdjVGWJQABzf3Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T10:06:58Z"
    mac: ENC[AES256_GCM,data:qdzSZKPV2k0zQ/qvbREk83fs/09ylW3R6hAkACuQBA/hYq3EjhaC21x8HQ7VQs5nM5n9Z1xeu20GKcJq5BdZKVxcO2Y6RSkxTba3bXC9VBfssujRm67qwQQ6lDWmZixS2OW64NtBQPU5a+gp/ahyEWjdNPZzYGBHMNB1fS0QS/0=,iv:1EJiy2V5IuodfBdMsGzcN3FY2/KFP2S7/FRgGz2gELY=,tag:rPHaxDk72mv9GKj85ZmlOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
