apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: homepage
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:D/m7ho24Z7IYw3aC3B84Av6gS5HVyQJ21zg1C9sVqMRKYjgglLGgzx4iXD4=,iv:HoURry7IlY7nylz9CFrQBtAwJRsF8bZa328Poin6utw=,tag:oxPLvIYFuKrG2LnH/n05Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNDJnb3BiL2xxdXJkR1Fr
            U0pSbURHL2JTenJ4TmlIU2grTC9LaENIZWxzCmEwYWJmN1RyVTBnUUlUNkxnRUpz
            NXFSR29abGpXZzhSbUJOcDlNSVhFbUEKLS0tIHRCcUo4UUt4dXdoUDlpZXdkOGdP
            V0FTa1V4RWN3bmR6anZLVU1lK3p5RFEKXINLowy96fhqejopYObOfKwtaRRYoW/b
            h3fQzRe4MD1yKs849PWlW5hFf6y1ut+6gbsjnZAbNV/ZrlhNzc0FaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T06:02:21Z"
    mac: ENC[AES256_GCM,data:EI7dwcby6q8S0E27S+5qNnLOHcRYRokLxLy5gV2yP0NdONfF3bawb5Br/H1tPiRJsILVlZXvOPe9XcDQStHPA1Oy4dMIcfaIirpaH7GcDGxnkn9mGluduH4AnQOPEYgdj6FYH/63teaVXnHD3Bi0A6RbCCkq1UuGeQKfdYtd6OU=,iv:EXi6X+Sgf8VF/0SDaKemYEc7XtsqmjuFgQ1PC4KfY28=,tag:detQXjG2a/rf2Yg7La+Edw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
