apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: homepage
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:sZG/yCGBxbI=,iv:+0GJs4BAfH4h485G9V+39FjNWO8+Cku/6/Ag9uEt+Yg=,tag:Xn6PuoRlyxLEK6RZVUCs8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dVJra1FESkYwVnFHUWhN
            ZVBERDB2aHdoQm9mTFZQdXVjSzA1TkFqTkhFCk82LzZmUk14SVhvb3hIeFptdW5L
            UXhPODhsVmYwSjVkdVdXZTdOSDkwTzQKLS0tIHJxRkliWDd3WFBXSjhCU0NiT2R1
            UWdUeVhodFVPL0dUZnNqRnFiNTQwR2sKnepXx9udJO61DRDSY+ubz1KY4zMOz6JS
            C8smu9GgwNZoXHFdqYfj+LBmdQIL7ptIPlchlIUvKDP5deHMFudJcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T07:10:50Z"
    mac: ENC[AES256_GCM,data:6ZlT/YMZrJO18Z0lQDEBwzKYFy8Ed5DQ88DIjVSdA1ld7KSNL6oFdHs7mlRdWXcY01fxMIxZlS2mxq77XoXMRQiqWo0oM1xGarAicnGG1S3LYNF9gB545bdC0aVoS//vcJPjUixgJWhcuj9ngIFijXKyyZaTRFBhdmBLP4ip6FM=,iv:8J7jRpWA/pUQNLijJpCk0OfgFbpu9PoGI7/ppJz+jtw=,tag:++MwH9T3ghkRKvmnS39+gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
