apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:do2yHrmYYOg=,iv:NIxGP18QOPj0EfBoUN73+BN8mWnA8OpHALoz/N8ORBk=,tag:ULrcUJbnFOtm7ws/UR/o6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRUdnbWladGROWFhRZ08y
            eEZYMSt0Ly9WbkVJTjgzNHN2dktNS1FpVzFnCjBuS2ErUk1STFBLckpac01uVUJa
            TWJXZnNsTlp4TTZPWVJLZUpCVlREYkkKLS0tIFprV09sWVp4RjB4NlNUMU9rdk1W
            RHlFZU9QT0cwRm5UNmJOVVdpOTd3UVUK+keDAI2UihHAORR3T0BEWPjZ9F8Wibgj
            SwXBbL7iymPcGRRktYTs28RtZUzbYE44Ebe71/RpYMRazE+U9N5hZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-24T20:59:41Z"
    mac: ENC[AES256_GCM,data:XQ0sH+APgVxPu8mVcc7fkrmfnlyglA54J6lKGpyvQ5W+fOyNMo3nxx2XP/dagHx28etaXieQisFcDThiuLhuVqavV+W29Tm/uK7Sj1hoBQPK4A86Er44dpgEQizL+SUUVjqmGaGt0beLH7leh+Us36TTAPm+9t77Et2IEiNhJfU=,iv:cmc03K8osw/qK4EpARZR4oqxccqNkcokV8dIHpCyigc=,tag:oAVC52JC18TGMjZNxEXhZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
