apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: FTLCONF_webserver_api_password
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: password
        - name: FTLCONF_LOCAL_IPV4
          value: "0.0.0.0"
        - name: FTLCONF_dns_upstreams
          value: "8.8.8.8"
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: pihole-etc
          mountPath: /etc/pihole
        - name: custom-dnsmasq-volume
          mountPath: /etc/dnsmasq.d/99-wildcard.conf
          subPath: 99-wildcard.conf
      volumes:
      - name: pihole-etc
        persistentVolumeClaim:
          claimName: pihole-etc-pvc
      - name: custom-dnsmasq-volume
        configMap:
          name: pihole-custom-dnsmasq
