apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - 01-namespace.yaml
  - 02-pvc.yaml
  - 03-secret.sops.yaml
  - 04-deployment.yaml
  - 05-service.yaml
  - pihole-custom-dnsmasq-configmap.yaml
