apiVersion: v1
kind: Service
metadata:
  name: bentopdf
  namespace: bentopdf
  labels:
    app.kubernetes.io/name: bentopdf
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bentopdf
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bentopdf-ingress
  namespace: bentopdf
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  labels:
    app.kubernetes.io/name: bentopdf
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - pdf.littlehomelab.com
      secretName: pdf-littlehomelab-tls
  rules:
  - host: pdf.littlehomelab.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bentopdf
            port:
              number: 80
