apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    admin.password: ENC[AES256_GCM,data:TiftWrQuoJqGvhr7ak7D+zsOLC441j8LAkffA0zmUMsL9izzXOdj8gue4odIE3hopdZTL8O24B/R9kCp,iv:AT9dF1h1+3RO70pcnRGXAaipK33mbTKe9jbSsg/gu8M=,tag:0uOoPKH8/7izIPaoTqS0eQ==,type:str]
    oidc.authelia.clientSecret: ENC[AES256_GCM,data:WpfH8jPMjJsKVOEijCG+HOi7uTD0NKBt40KZdgpboUE=,iv:tEa6wwlHSrqhhF8UOh+isdqpgilCMrj4OrQB3X31YZk=,tag:KQftlkVUN4bDp/yK3szDKA==,type:str]
    server.secretkey: ENC[AES256_GCM,data:mkez+PwcJEdD3jNAWgOYNrw6vhHxLCizFJE+m1jWCXDWpuekK9UeXTta6hE=,iv:G50hQLuHcueClK1xXafUdOHZqAr9M5fh4dpxy1yiaJI=,tag:HF4feF9Wj2uazQFrSylTSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwblB3RExZU2tNeE5GNlpu
            di9jbnpCK3Z2Q0l5aXVQQnlNdlNPWm9PTGlBClJCVEluclgrMldCcllEMXB2T0d5
            WFJCQU4zcGpsS3pCU3RLUUdlRnVLY3MKLS0tIHBjVW1NVm1DanBxZGFmc0JRWjB2
            Rm5yaUVSdEpFV3p2QVBHMDJHcnY2cEkKcVVweAmE06EZ00Y1+IsqiczQvgvQDOtP
            SoVQ0gp98jpQpVofwxF1zoPK7CEcUVO7WVYzSEYn4c6vcS9+eNko5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T10:34:54Z"
    mac: ENC[AES256_GCM,data:z9hYeZUsN/8s4msHQDAoDSgxYe+R2AZ0aBj/U06cUgwEsrXxUKaF87wkP57jocui8MUp2yDWKayFDyI8Y5BtHU1FlKMmiPa1lHyqXc2PmTUhwakvNtpU8D6V51XaL+4zzlapuwn/7p8kR0f8sbfj4rmhh4cdZcTaOrKA0MxCsDU=,iv:Fax7j1ViT9DJA2EYhpN9JSaplh60njN5fNHXswSHUNM=,tag:V9mZIqzWxBnFHWPFN8vtNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
