apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
type: Opaque
stringData:
    oidc.authelia.clientSecret: ENC[AES256_GCM,data:WpfH8jPMjJsKVOEijCG+HOi7uTD0NKBt40KZdgpboUE=,iv:tEa6wwlHSrqhhF8UOh+isdqpgilCMrj4OrQB3X31YZk=,tag:KQftlkVUN4bDp/yK3szDKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwblB3RExZU2tNeE5GNlpu
            di9jbnpCK3Z2Q0l5aXVQQnlNdlNPWm9PTGlBClJCVEluclgrMldCcllEMXB2T0d5
            WFJCQU4zcGpsS3pCU3RLUUdlRnVLY3MKLS0tIHBjVW1NVm1DanBxZGFmc0JRWjB2
            Rm5yaUVSdEpFV3p2QVBHMDJHcnY2cEkKcVVweAmE06EZ00Y1+IsqiczQvgvQDOtP
            SoVQ0gp98jpQpVofwxF1zoPK7CEcUVO7WVYzSEYn4c6vcS9+eNko5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T10:21:32Z"
    mac: ENC[AES256_GCM,data:mmEGjUn/67IpgSJ2mMRNSbDTkN/jEqetKQQREsU5rzetTSsJOxg24XZg6WIIXI1bht2oi/y2w9PdpUOjQ+CnLDvmCa9qhythTGwQFFemj4SeKynby47e2oKMJQhQblirFqsd8Izhp8Uw7HnQkHAtyJX2+Hycy3Vnx/mUOOMU2fY=,iv:7V0rL4iEk/YbInYANLBZhCjnKvdnY9HOtjuUijlHoek=,tag:6vRd9mo0KqPEva203JdbIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
