apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
    admin.password: ENC[AES256_GCM,data:TiftWrQuoJqGvhr7ak7D+zsOLC441j8LAkffA0zmUMsL9izzXOdj8gue4odIE3hopdZTL8O24B/R9kCp,iv:AT9dF1h1+3RO70pcnRGXAaipK33mbTKe9jbSsg/gu8M=,tag:0uOoPKH8/7izIPaoTqS0eQ==,type:str]
    oidc.authelia.clientSecret: ENC[AES256_GCM,data:WpfH8jPMjJsKVOEijCG+HOi7uTD0NKBt40KZdgpboUE=,iv:tEa6wwlHSrqhhF8UOh+isdqpgilCMrj4OrQB3X31YZk=,tag:KQftlkVUN4bDp/yK3szDKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17shk2n5pcma33mvzapxh5z48phjhnpskm9juxdvg8aepzn59ja2q6fafg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwblB3RExZU2tNeE5GNlpu
            di9jbnpCK3Z2Q0l5aXVQQnlNdlNPWm9PTGlBClJCVEluclgrMldCcllEMXB2T0d5
            WFJCQU4zcGpsS3pCU3RLUUdlRnVLY3MKLS0tIHBjVW1NVm1DanBxZGFmc0JRWjB2
            Rm5yaUVSdEpFV3p2QVBHMDJHcnY2cEkKcVVweAmE06EZ00Y1+IsqiczQvgvQDOtP
            SoVQ0gp98jpQpVofwxF1zoPK7CEcUVO7WVYzSEYn4c6vcS9+eNko5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T10:30:24Z"
    mac: ENC[AES256_GCM,data:W5QQrxe5gydaUi1PGFmXmntj6OxwpPxPBHCx/AHu3fUbAVSrKf/RMeXGXWaGHNaLXY/ix7uhOMF8mPgOiieTZzk3Tjnnkiro40relQuf7553mc9FiawSA2/Vj6luDfMaG3zl9xvkHWRuR9Na7812u6hNhq5JwgVzl14MaUYxPx4=,iv:Z2JlM0oxha/P72JKzFPDRBdXXx3eboeW7tx49pA/J1E=,tag:od9nCd8qASlwAUogXSdwzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
