apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

# 1. Standalone resources to create
resources:
  - CMPconfigmap.yaml           # Exact casing from your folder
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-secret.sops.yaml
  - ingress.yaml
  - argocd-repo-server-base.yaml
# 2. Strategic merge patches to modify existing resources
patchesStrategicMerge:
  - repo-server-patch.yaml
